version: '3.1'

services:

  discovery:
    image: orlandirafael/sicredi-eureka-server
    container_name: sicredi-eureka-server
    build:
      context: ./sicredi-eureka-server
      args:
        JAR_FILE: target/sicredi-eureka-server-${DISCOVERY_VERSION}.jar
    ports:
      - "8761:8761"

  api-gateway:
    image: orlandirafael/sicredi-api-gateway
    container_name: sicredi-api-gateway
    ports:
      - "8888:8888"
    build:
      context: ./sicredi-api-gateway
      args:
        JAR_FILE: target/sicredi-api-gateway-${GATEWAY_VERSION}.jar
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
      - VOTING_URL=http://sicredi-voting:8080
    links:
      - discovery

  sicredi-voting:
    image: orlandirafael/sicredi-voting-service
    restart: always
    build:
      context: ./sicredi-voting-service
      args:
        JAR_FILE: target/sicredi-voting-service-${VOTING_VERSION}.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_SERVER=http://discovery:8761/eureka
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      discovery:
        condition: service_started
      postgresql:
        condition: service_healthy
    links:
      - discovery
      - rabbitmq

  postgresql:
    container_name: sicredi-voting-postgres
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ='America/Sao_Paulo'
      - PGTZ='GMT-3'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  resultmq:
    container_name: sicredi-resultmq-service
    image: orlandirafael/sicredi-resultmq-service
    restart: always
    build:
      context: ./sicredi-resultmq-service
      args:
        JAR_FILE: target/sicredi-resultmq-service-${RESULTMQ_VERSION}.jar
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
